## Stats and figures for "Uncovering multiple influences on space use by deer mice using NEON data"
# This script contains analysis of the home ranges of Peromyscus captured >4x as adults across all NEON sites. 
# Inputs: 'ao_ranges' dataframe as generated by 'deer-mouse_make-ranges' script.

##### Load libraries
library(ggplot2)
library(dplyr)
library(car)
library(lme4)
library(ggnewscale)
library(ggpubr)
library(performance)
library('emmeans')
library(ggeffects)

###### load dataframe created in 'get_home_ranges' script
load("all_ao_ranges.RData") 

# convert variables to factor for analysis:
ao_ranges$sex = as.factor(ao_ranges$sex)
ao_ranges$vegType = as.factor(ao_ranges$vegType)

# rearrange factor levels for later plotting
ao_ranges <- ao_ranges %>%
  mutate(vegType = factor(vegType, levels=c("forest", "shrubland", "grassland")))

###############
#### STATS ####
###############

##### Modeling home range vs. environmental and intrinsic factors
# build models for comparison using AIC

# no interaction terms:
m1=glmer(UD ~ sex + vegType + meanMNKA + latitude + bodyCondition + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

# models with interactions:
m2=glmer(UD ~ sex + vegType * latitude + meanMNKA + bodyCondition + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m3=glmer(UD ~ sex * bodyCondition + vegType + latitude + meanMNKA  + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m4=glmer(UD ~ sex * bodyCondition + vegType * latitude + meanMNKA  + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m5=glmer(UD ~ sex + bodyCondition * latitude + vegType  + meanMNKA  + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m6=glmer(UD ~  bodyCondition + latitude + sex * vegType * meanMNKA  + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m7=glmer(UD ~  bodyCondition + sex + latitude  * vegType * meanMNKA  +
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m8=glmer(UD ~  bodyCondition * sex + latitude * vegType * meanMNKA  +
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m9=glmer(UD ~  bodyCondition * sex * meanMNKA + latitude * vegType   + 
           (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m10=glmer(UD ~  vegType + sex + latitude * bodyCondition * meanMNKA  + 
            (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m11=glmer(UD ~ sex * meanMNKA + latitude + bodyCondition +  vegType +
            (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

m12=glmer(UD ~ sex * meanMNKA * bodyCondition + latitude  +  vegType +
            (1 | year) + (1 | site), data = ao_ranges, family = Gamma(link = "log"))

# compare models to determine preferred model by AIC
# checking models w/ performance score
compare_performance(m2,m1,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12, rank=TRUE)
# generate Table S1 by ranking models in order of support
compare_performance(m8,m6,m3,m7,m12,m9,m4,m1,m11,m5,m2,m10)

# best fit model is m8
check_model(m8) # check model assumptions
Anova(m8) # get analysis of deviance table

# post hoc for selected model
pairs(emmeans(m9, ~ vegType))


#################
#### FIGURES ####
#################


### HR v. Sex (Figure 1)
ggplot(ao_ranges, aes(x=sex, y=UD, fill=sex, color=sex)) +
  xlab("Sex") +
  ylab(expression("Home Range Area (m"^2*")")) +
  geom_boxplot(alpha = 0.8) +
  scale_x_discrete(labels=c('Female','Male')) +
  scale_fill_manual(values=c("#ED8612", "#1279ED")) +
  scale_color_manual(values=c("#7f480a", "#093f7b")) +
  theme(legend.position="none",
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 23, margin = margin(t=4,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 23, margin = margin(t=0,r=4,b=0,l=0)),
        axis.text = element_text(size=20))


### HR v. bodyCondition x sex (Figure 2)
# get effect of body condition as an object for plotting
emmeans.bCxSex <- as.data.frame(ggemmeans(m8, terms = c('bodyCondition','sex')))
# plot
ggplot(emmeans.bCxSex, aes(x, predicted)) + 
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high,
                  group = group, fill = group),
              alpha = 0.2, linewidth = 0.6, show.legend = F) +
  geom_point(data = ao_ranges, aes(x = bodyCondition, y = UD,
                                   color = sex, fill = sex, shape = sex),
             alpha = 0.5, size = 4) +
  geom_line(aes(x, predicted, group = group, color = group), linewidth = 1) +
  xlab("Body Condition") +
  ylab(expression("Home Range Area (m"^2*")")) +
  scale_fill_manual(labels=c('Female','Male'),
                    values=c('#ED8612', '#1279ED')) +
  scale_color_manual(labels=c('Female','Male'),
                     values=c('#ED8612', '#1279ED')) +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  guides(fill = 'none') +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.82,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))


# scale_fill_manual(values=c("#9bd7a3", '#bfb7e9', "#feeeab")) +
# scale_color_manual(values=c("#296732", '#2c216a', "#c19c03")) +
  
### HR v. vegType (Figure 3)
ggplot() +
  xlab("Habitat Type") +
  ylab(expression("Home Range Area (m"^2*")")) +
  geom_boxplot(data = ao_ranges,
               aes(x=vegType, y=UD, color=vegType, fill=vegType),
               alpha=0.65) +
  scale_fill_manual(values=c("#7dcb88", '#978AE7', "#FDDC51")) +
  scale_color_manual(values=c("#1F4D26", '#1C1257', "#786102")) +
  annotate("text", x = 1, y = 9700, label = "A", size = 8) + 
  annotate("text", x = 2, y = 9700, label = "AB", size = 8) + 
  annotate("text", x = 3, y = 9700, label = "B", size = 8) + 
  theme(legend.position="none",
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 23, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 23, margin = margin(t=0,r=4,b=0,l=0)),
        axis.text = element_text(size=20))


### HR v. Latitude (Figure 4)
# get effect of latitude as an object for plotting
effect.lat <- as.data.frame(ggeffect(m8, terms = c("latitude")))
# plot
ggplot(effect.lat, aes(x, predicted)) + 
  geom_point(data = ao_ranges, aes(x = latitude, y = UD,
                                   color=sex, fill=sex, shape=sex),
             alpha = 0.6, size = 4) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),
              alpha = 0.2, linewidth = 0.6, show.legend = F) +
  geom_line(linewidth = 1.2) +
  xlab("Latitude") +
  ylab(expression("Home Range Area (m"^2*")")) +
  scale_fill_manual(labels=c('Female','Male'),
                    values=c('#ED8612', '#1279ED')) +
  scale_color_manual(labels=c('Female','Male'),
                     values=c('#ED8612', '#1279ED')) +
  scale_shape_manual(labels=c('Female','Male'),
                     values=c('circle','triangle')) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.14,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))

### HR v. MNKA (Fig 5)
# get effect of meanMNKA as an object for plotting
emmeans.mnka <- as.data.frame(ggemmeans(m8, terms = c('meanMNKA')))
# plot
ggplot(emmeans.mnka, aes(x, predicted)) +
  geom_point(data = ao_ranges, aes(x = meanMNKA, y = UD, color=sex, fill=sex, shape=sex),
             alpha = 0.6, size = 4) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),
              alpha = 0.2, linewidth = 0.6, show.legend = F) +
  geom_line(linewidth = 1.2) +
  xlab("Animal Density") +
  ylab(expression("Home Range Area (m"^2*")")) +
  scale_color_manual(labels=c('Female','Male'),values=c('#ED8612', '#1279ED')) +
  scale_fill_manual(labels=c('Female','Male'),values=c('#ED8612', '#1279ED')) +
  scale_shape_manual(labels=c('Female','Male'),values=c('circle','triangle')) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.8,0.87),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))


##### HR by MNKA, with color and trend lines by latitude, faceted by habitat type (Figure 6)
# first, create needed model predictions
emmeans.mnkaXlatxvegType <- as.data.frame(ggemmeans(m8, terms = c("meanMNKA",'latitude','vegType')))
# convert group to numeric 
emmeans.mnkaXlatxvegType$group <- as.numeric(as.character(emmeans.mnkaXlatxvegType$group))
# split by vegType for plotting
emmeans.mlv.forest <- emmeans.mnkaXlatxvegType[emmeans.mnkaXlatxvegType$facet=='forest',]
emmeans.mlv.grassland <- emmeans.mnkaXlatxvegType[emmeans.mnkaXlatxvegType$facet=='grassland',]
emmeans.mlv.shrubland <- emmeans.mnkaXlatxvegType[emmeans.mnkaXlatxvegType$facet=='shrubland',]

### Create panels for each vegType
# HR v. lat * MNKA * vegType (forest)
mnkaVlat.forest<-ggplot(emmeans.mlv.forest, aes(x, predicted)) + 
  geom_point(data = ao_ranges[ao_ranges$vegType=='forest',], aes(x = meanMNKA,
                                                                    y = UD, color = latitude),
             alpha = 0.5, size = 4) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group,
                  group = group),
              alpha = 0.2, linewidth = 0.6, show.legend = F) +
  geom_line(aes(x, predicted, group = group, color = group), linewidth = 1) +
  ggtitle('A. Forest') +
  scale_color_gradient(name = 'Latitude',
                       high = '#1F4D26',
                       low = '#7dcb88') +
  scale_fill_gradient(name = 'Latitude',
                       high = '#1F4D26',
                       low = '#7dcb88') +
  ylab(expression("Home Range Area (m"^2*")")) +
  xlab('') +
  ylim(0, 10225) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.85,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))

# HR v. lat * MNKA * vegType (shrubland)
mnkaVlat.shrubland<-ggplot(emmeans.mlv.shrubland, aes(x, predicted)) + 
  geom_point(data = ao_ranges[ao_ranges$vegType=='shrubland',], aes(x = meanMNKA,
                                                                    y = UD, color = latitude),
             alpha = 0.5, size = 4) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group, group = group),
              alpha = 0.2, linewidth = 0.6, show.legend = F) +
  geom_line(aes(x, predicted, group = group, color = group), linewidth = 1) +
  ggtitle('B. Shrubland') +
  scale_color_gradient(name = 'Latitude',
                       high = '#1C1257',
                       low = '#978AE7') +
  scale_fill_gradient(name = 'Latitude',
                      high = '#1C1257',
                      low = '#978AE7') +
  xlab("Animal Density") +
  ylim(0, 10225) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 26, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_blank(),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.85,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))

# HR v. lat * MNKA * vegType (grassland)
mnkaVlat.grassland<-ggplot(emmeans.mlv.grassland, aes(x, predicted)) + 
  geom_point(data = ao_ranges[ao_ranges$vegType=='grassland',], aes(x = meanMNKA,
                                                                    y = UD, color = latitude),
             alpha = 0.5, size = 4) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = group, group = group),
              alpha = 0.2, linewidth = 0.6, show.legend = F) +
  geom_line(aes(x, predicted, group = group, color = group), linewidth = 1) +
  ggtitle('C. Grassland') +
  scale_color_gradient(name = 'Latitude',
                       high = "#786102",
                       low = "#FDDC51") +
  scale_fill_gradient(name = 'Latitude',
                       high = "#786102",
                       low = "#FDDC51") +
  xlab('') +
  ylim(0, 10225) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_blank(),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.85,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))

# plot all together
ggarrange(mnkaVlat.forest, mnkaVlat.shrubland, mnkaVlat.grassland, ncol = 3, nrow = 1)


#########################
##### SUPP MATT FIGS ####
#########################

# mnka v. latitude
ggplot(ao_ranges, aes(x=latitude, y=meanMNKA)) +
  ggtitle("Peromyscus Density vs. Latitude") +
  xlab("Latitude") +
  ylab(expression("Mean MNKA")) +
  geom_point(size = 4, color = 'darkgrey', alpha=0.85) +
  geom_smooth(method='glm', se=TRUE, fullrange=TRUE, size=2) +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x = element_text(size = 20, margin = margin(t=10,r=0,b=0,l=0)),
        axis.title.y = element_text(size = 20, margin = margin(t=0,r=10,b=0,l=0)),
        axis.text = element_text(size=15),
        plot.title = element_text(size = 22, face='bold'),
        legend.position = c(0.14,0.85),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        legend.key = element_rect(fill = 'white'),
        legend.key.height = unit(1,'cm'),
        legend.background = element_rect(fill = 'white',color = 'black'))
